const mainOptionsList = [
  { id: 1, label: "PosNeg Lists", value: 1 },
  { id: 2, label: "Exception Lists", value: 2 },
  { id: 3, label: "Risky Airports", value: 3 },
  { id: 4, label: "Risky Prodcuts", value: 4 },
  { id: 5, label: "OFA CList", value: 5 },
  { id: 6, label: "Domestic Countries", value: 6 },
  { id: 6, label: "Free Domains", value: 7 },
];

const domainTypeList = [
  { id: 1, label: "Address Info", value: 1 },
  { id: 2, label: "DeviceInsight Print", value: 2 },
  { id: 3, label: "Email", value: 3 },
  { id: 4, label: "Resolve ID", value: 4 },
  { id: 5, label: "User Account", value: 5 },
  { id: 6, label: "Username", value: 6 },
  { id: 7, label: "Accept", value: 7 },
  { id: 8, label: "Accept Charset", value: 8 },
  { id: 9, label: "Accept Encoding", value: 9 },
  { id: 10, label: "Accept Language Code", value: 10 },
  { id: 11, label: "User Agent", value: 11 },
  { id: 12, label: "User Agent OS", value: 12 },
  { id: 13, label: "User Agent Type", value: 13 },
  { id: 14, label: "PHONE", value: 14 },
  { id: 15, label: "Andriod ID", value: 15 },
  { id: 16, label: "Device Carrier Name", value: 16 },
  { id: 17, label: "Device Name", value: 17 },
  { id: 18, label: "Device Type", value: 18 },
  { id: 19, label: "Device Type Keyword", value: 19 },
  { id: 20, label: "IP", value: 20 },
  { id: 21, label: "IP Address C Block", value: 21 },
  { id: 22, label: "ISP Name", value: 22 },
  { id: 23, label: "Language", value: 23 },
  { id: 24, label: "Mobile Device ID", value: 24 },
  { id: 25, label: "Navigator Platform", value: 25 },
  { id: 26, label: "Resolved ID", value: 26 },
  { id: 27, label: "Screen Resolution", value: 27 },
  { id: 28, label: "Sha 1 Sim Serial Number", value: 28 },
  { id: 29, label: "Sha 1 Wifi Mac", value: 29 },
  { id: 30, label: "Wafer ID", value: 30 },
  { id: 31, label: "Email", value: 31 },
  { id: 32, label: "Email Domain", value: 32 },
  { id: 33, label: "Email TLD", value: 33 },
  { id: 34, label: "Email User", value: 34 },
  { id: 35, label: "Credit Card BIN", value: 35 },
  { id: 36, label: "Credit Card Hashed", value: 36 },
  { id: 37, label: "Credit Card Type", value: 37 },
  { id: 38, label: "Financial Account Number", value: 38 },
  { id: 39, label: "Payment Subtype", value: 39 },
  { id: 40, label: "Payment Type", value: 40 },
  { id: 41, label: "Routing Number", value: 41 },
  { id: 42, label: "Address Info", value: 42 },
  { id: 43, label: "City", value: 43 },
  { id: 44, label: "Company", value: 44 },
  { id: 45, label: "Country code", value: 45 },
  { id: 46, label: "Name", value: 46 },
  { id: 47, label: "Postal Code", value: 47 },
  { id: 48, label: "State", value: 48 },
  { id: 49, label: "Time Zone", value: 49 },
  { id: 50, label: "Lexical", value: 50 },
  { id: 51, label: "Organization ID", value: 51 },
  { id: 52, label: "Promatonal Code", value: 52 },
  { id: 53, label: "Ship Method Type", value: 53 },
  { id: 54, label: "Specialty Purchase", value: 54 },
  { id: 55, label: "Encrpted Password", value: 55 },
  { id: 56, label: "mothers Maiden Name", value: 56 },
  { id: 57, label: "SSN Tax ID", value: 57 },
  { id: 58, label: "User Account", value: 58 },
  { id: 59, label: "User Cookie", value: 59 },
  { id: 60, label: "Username", value: 60 },
];
const orgList = [
  { id: 1, label: "BONDORG", value: 1 },
  { id: 2, label: "03code", value: 2 },
  { id: 3, label: "0981", value: 3 },
  {
    id: 4,
    label: "09877",
    value: 4,
  },
];
const posNegList = [
  { id: 1, label: "Negative", value: 1 },
  { id: 2, label: "Positive", value: 2 },
  { id: 3, label: "XSpecial", value: 3 },
];
const countryCodeList = [];
export { mainOptionsList, domainTypeList, orgList, posNegList, countryCodeList };
